id: A8C875B4F
title: Prayer to the Sovereign of Dharma and Retinue
type: translation
pechas:
- IBBFBEB5B
- I14CD134C
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 13:11:09.570896
  last_modified_at: 2023-01-04 13:11:09.570906
  collections:
  - Mipham Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  IBBFBEB5B/143A: 8FC7
  I14CD134C/9FF0: 8FC7
